machines:
  - EN: Refining
    CN: 精炼机
    size: [3, 3]
  - EN: Shredding
    CN: 粉碎机
    size: [3, 3]
  - EN: Fitting
    CN: 配件机
    size: [3, 3]
  - EN: Moulding
    CN: 塑形机
    size: [3, 3]
  - EN: Seed-Picking
    CN: 采种机
    size: [5, 5]
  - EN: Planting
    CN: 种植机
    size: [5, 5]
  - EN: Gearing
    CN: 装备原件机
    size: [3, 6]
  - EN: Filling
    CN: 灌装机
    size: [3, 6]
  - EN: Packing
    CN: 封装机
    size: [3, 6]
  - EN: Grinding
    CN: 研磨机
    size: [3, 6]
  - EN: Core
    CN: 协议核心
    size: [9, 9]
    inputs:
      - [0, 1, 2]
      - [0, 2, 2]
      - [0, 3, 2]
      - [0, 4, 2]
      - [0, 5, 2]
      - [0, 6, 2]
      - [0, 7, 2]
      - [0, 8, 2]
      - [8, 1]
      - [8, 2]
      - [8, 3]
      - [8, 4]
      - [8, 5]
      - [8, 6]
      - [8, 7]
      - [8, 8]
    outputs:
      - [1, 0, 3]
      - [4, 0, 3]
      - [7, 0, 3]
      - [1, 8, 1]
      - [4, 8, 1]
      - [7, 8, 1]
  - EN: Depot-Loader
    CN: 仓库存货口
    size: [1, 3]
    inputs:
      - [0, 1]
    outputs: []
    depot: true
  - EN: Depot-Unloader
    CN: 仓库取货口
    size: [1, 3]
    inputs: []
    outputs:
      - [0, 1]
    depot: true
  - EN: Protocol-Stash
    CN: 协议储存箱
    size: [3, 3]
  - EN: AbstractNode
    CN: 抽象点
    size: [0, 0]
    inputs: []
    outputs: []
    public: false
  
power:
  size: [2, 2]
  range: [5, 6]

rewards:
  belt_extend: 1.0
  alone_belt: -0.5
  connected: 10.0
  all_connected: 40.0
  unmatched: -20.0
  finished: 100.0
  all_machine_placed: 20.0
  machine_powered: 3.0
  dead_end: -100.0

levels:
  - h: [7, 10]
    w: [7, 10]
    max_output_ports: 1
    num_machines: [1, 1]
    machine_range: [0, 5]
    input_degrees: [1, 1]
    core_prob: 0.0
    depot_edges: [0]
  - h: [9, 12]
    w: [9, 12]
    max_output_ports: 2
    num_machines: [1, 3]
    machine_range: [0, 9]
    input_degrees: [1, 1]
    core_prob: 0.0
    depot_edges: [0]
  - h: [12, 15]
    w: [12, 15]
    max_output_ports: 2
    num_machines: [3, 5]
    machine_range: [0, 9]
    input_degrees: [1, 2]
    core_prob: 0.0
    depot_edges: [0]
  - h: [15, 18]
    w: [15, 18]
    max_output_ports: 4
    num_machines: [5, 8]
    machine_range: [0, 9]
    input_degrees: [1, 3]
    core_prob: 0.5
    depot_edges: [0]
  - h: [18, 24]
    w: [18, 24]
    max_output_ports: 6
    num_machines: [8, 12]
    machine_range: [0, 9]
    input_degrees: [1, 3]
    core_prob: 0.5
    depot_edges: [0]
  - h: [18, 24]
    w: [18, 24]
    max_output_ports: 6
    num_machines: [10, 15]
    machine_range: [0, 9]
    input_degrees: [1, 3]
    core_prob: 0.5
    depot_edges: [0, 3]
  - h: [30, 40]
    w: [30, 40]
    max_output_ports: 10
    num_machines: [15, 20]
    machine_range: [0, 9]
    input_degrees: [1, 4]
    core_prob: 0.5
    depot_edges: [0, 3]
  - h: [40, 50]
    w: [40, 50]
    max_output_ports: 12
    num_machines: [25, 35]
    machine_range: [0, 9]
    input_degrees: [1, 4]
    core_prob: 0.5
    depot_edges: [0, 3]
